---
name: PocKit
version: 0.0.1
main: LemoniqPvP\PocKit\Main
api: 4.0.0

commands:
  kiteditor:
    permission: pockit.command.kiteditor
    description: Edit kits visually
  createkit:
    permission: pockit.command.createkit
    description: Create new kits
  kit:
    permission: pockit.command.kit
    description: Get a kit to help you out
  
permissions:
  pockit.command.kiteditor:
    description: Edit kits visually
    default: op
  
  pockit.command.createkit:
    description: Create new kits
    default: op

  pockit.command.kit:
    description: Use kits
    default: true

...
